services:
  dst:
    build:
      context: .
    image: niudea/dst:latest
    container_name: dst
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "10999:10999/udp"
      - "10998:10998/udp"
      - "27017:27017/udp"
      - "8767:8767/udp"
    volumes:
      - ./runtime/klei:/root/.klei/DoNotStarveTogether
      - ./runtime/dst:/root/steam/dst
